openapi: 3.1.0
info:
  title: API de Escalas da Igreja
  version: 1.0.0
  description: |
    API RESTful para gerenciamento de celebrações, disponibilidades e geração de escalas.
servers:
  - url: https://your-domain.com
paths:
  /api/celebrations:
    post:
      summary: CRUD de celebrações
      description: >
        Recebe um objeto JSON com `action` (`create`, `update`, `delete`) e
        `payload` contendo os campos da celebração. Requer autenticação do usuário
        com papel ADMIN.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
                  enum: [create, update, delete]
                payload:
                  type: object
              required:
                - action
      responses:
        '200':
          description: Operação realizada com sucesso
        '400':
          description: Erro na solicitação
        '401':
          description: Não autenticado
  /api/availabilities:
    post:
      summary: Criar ou atualizar disponibilidade
      description: >
        Marca a disponibilidade do membro logado para uma celebração.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                celebration_id:
                  type: string
                available:
                  type: boolean
              required: [celebration_id, available]
      responses:
        '200':
          description: Disponibilidade registrada
        '400':
          description: Erro na solicitação
        '401':
          description: Não autenticado
  /api/schedules/generate:
    post:
      summary: Gerar escala
      description: >
        Gera uma nova escala para o mês informado. A query `month` deve ser
        no formato `YYYY-MM`. Opcionalmente, o corpo pode conter
        `ministry` (nome do ministério a regenerar) e `preserveLocked` (boolean) para
        preservar posições travadas.
      parameters:
        - in: query
          name: month
          required: true
          schema:
            type: string
            pattern: '^\d{4}-\d{2}$'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ministry:
                  type: string
                preserveLocked:
                  type: boolean
      responses:
        '200':
          description: Escala gerada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  scheduleRunId:
                    type: string
                  assignments:
                    type: array
                    items:
                      type: object
        '400':
          description: Erro de validação
        '401':
          description: Não autenticado
  /api/schedules/publish:
    post:
      summary: Publicar escala
      description: >
        Altera o status de uma schedule_run para `published`. A
        schedule_run deve existir e o usuário deve possuir papel ADMIN.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required: [id]
      responses:
        '200':
          description: Escala publicada com sucesso
        '400':
          description: Erro na solicitação
        '401':
          description: Não autenticado
  /api/schedules/{id}:
    get:
      summary: Obter detalhes de uma escala
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: format
          in: query
          required: false
          schema:
            type: string
            enum: [csv, pdf]
      responses:
        '200':
          description: >
            JSON com detalhes da escala ou um arquivo no formato especificado.
          content:
            application/json:
              schema:
                type: object
            text/csv:
              schema:
                type: string
                format: binary
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          description: Erro na solicitação
        '401':
          description: Não autenticado
        '404':
          description: Escala não encontrada